# Generated by Django 4.1 on 2022-08-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_docidenticao_pontoturistico_doc_identificacao"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DocIdenticao",
            new_name="DocIdenticacao",
        ),
    ]
